// Chakra imports
import {
  Box,
  Button,
  Flex,
  Grid,
  Icon,
  Image,
  Portal,
  Progress,
  SimpleGrid,
  Spacer,
  Stat,
  StatHelpText,
  StatLabel,
  StatNumber,
  Table,
  Tbody,
  Td,
  Text,
  Th,
  Thead,
  Tr,
  useColorMode,
  useColorModeValue,
  CircularProgress,
  CircularProgressLabel,
} from "@chakra-ui/react";
// assets

import logoChakra from "assets/svg/logo-white.svg";
// Custom components
import Card from "components/Card/Card.js";
import CardBody from "components/Card/CardBody.js";
import CardHeader from "components/Card/CardHeader.js";
import BarChart from "components/Charts/BarChart";
import LineChart from "components/Charts/LineChart";
import IconBox from "components/Icons/IconBox";
import Donut from "components/Charts/DonutChart"
// Custom icons
import {
  CartIcon,
  DocumentIcon,
  GlobeIcon,
  RocketIcon,
  StatsIcon,
  WalletIcon,
} from "components/Icons/Icons.js";
import DashboardTableRow from "components/Tables/DashboardTableRow";
import TimelineRow from "components/Tables/TimelineRow";
import React, { useState } from "react";
// react icons
import { BsArrowRight } from "react-icons/bs";
import { IoCheckmarkDoneCircleSharp } from "react-icons/io5";
import { dashboardTableData, timelineData } from "variables/general";
import {data1 , dataCredit, dataequity , dataetf, datamutualfund}from "Mock_Data/mockdata1";
var name = data1.profile.holders.holder[0].name
// assuming age 30 from mock data
var age = 30
// Calculating current Balance
var bal = data1.summary.currentBalance
// Calculating Net Worth
var asset = parseInt(bal) + parseInt(datamutualfund.summary.currentValue) + parseInt(dataequity.summary.currentValue) + parseInt(dataetf.summary.currentValue)
var loan = 124320
var liabilities = parseInt(dataCredit.summary.currentDue) + loan
var net = asset - liabilities
// Calculting debt ratio
var debtRatio = liabilities/ asset
// Calculating SHAURYA score with scorecard generated by the ML Model
if (age <= 30){
 var s1 = 150
}
if (age > 30 && age <=40){
 var s1 = 165
}
if (age > 40 && age <=50){
 var s1 = 185
}
if (age > 50 && age <=60){
 var s1 = 200
}
if (age > 60 && age <=70){
 var s1 = 210
}
if (age > 70){
 var s1 = 220
}
if(debtRatio <= 0.2){
   var s2 = 200
}
if(debtRatio > 0.2 && debtRatio <=0.4){
   var s2 = 225
}
if(debtRatio > 0.4 && debtRatio <=0.8){
   var s2 = 175
}
if(debtRatio > 0.8 && debtRatio <=1.0){
   var s2 = 150
}
if(debtRatio > 1.0 && debtRatio <=1.2){
   var s2 = 135
}
if(debtRatio > 1.2 && debtRatio <=1.4){
   var s2 = 110
}
if(debtRatio > 1.4 && debtRatio <=1.6){
   var s2 = 120
}
if(debtRatio > 1.6){
   var s2 = 110
}
if(bal <= 10000){
   var s3 = 120
}
if(bal > 10000 && bal <= 17000){
   var s3 = 140
}
if(bal > 17000 && bal <= 25000){
   var s3 = 150
}
if(bal > 25000 && bal <= 38000){
   var s3 = 200
}
if(bal > 38000 && bal <= 50000){
   var s3 = 225
}
if(bal > 50000 && bal <= 63000){
   var s3 = 230
}
if(bal > 63000){
   var s3 = 250
}

var score = s1 + s2 + s3

export default function Dashboard() {
 
  const value = "$100.000";
  // Chakra Color Mode
  const { colorMode, toggleColorMode } = useColorMode();
  const iconTeal = useColorModeValue("teal.300", "teal.300");
  const iconBoxInside = useColorModeValue("white", "white");
  const textColor = useColorModeValue("gray.700", "white");

  const overlayRef = React.useRef();

  // Dynamic credit score color
  const scoreColor = score > 700 ? "#00D4AA" : score >= 500 ? "#FFD166" : "#FF4D6D";

  return (
    <Flex flexDirection="column" pt={{ base: "120px", md: "75px" }}>
      <SimpleGrid columns={{ sm: 1, md: 2, xl: 4 }} spacing="24px">
        {/* SHAURYA Credit Score Card */}
        <Card minH="105px" borderLeft="4px solid #6C63FF" p="16px">
          <CardBody>
            <Flex flexDirection="row" align="center" justify="space-between" w="100%">
              <Stat>
                <StatLabel
                  fontSize="xs"
                  color="gray.400"
                  fontWeight="bold"
                  pb=".2rem"
                  textTransform="uppercase"
                >
                  SHAURYA Score
                </StatLabel>
                <Flex align="center">
                  <StatNumber fontSize="2xl" color={textColor} fontWeight="bold">
                    {score}
                  </StatNumber>
                </Flex>
              </Stat>
              <CircularProgress
                value={score}
                min={300}
                max={900}
                color={scoreColor}
                size="55px"
                thickness="10px"
              >
                <CircularProgressLabel fontSize="10px" fontWeight="bold" color={textColor}>
                  {score}
                </CircularProgressLabel>
              </CircularProgress>
            </Flex>
          </CardBody>
        </Card>

        {/* Net Worth Card */}
        <Card minH="105px" borderLeft="4px solid #6C63FF" p="16px">
          <CardBody>
            <Flex flexDirection="row" align="center" justify="space-between" w="100%">
              <Stat>
                <StatLabel
                  fontSize="xs"
                  color="gray.400"
                  fontWeight="bold"
                  pb=".2rem"
                  textTransform="uppercase"
                >
                  Net Worth
                </StatLabel>
                <Flex align="baseline">
                  <StatNumber fontSize="2xl" color={textColor} fontWeight="bold">
                    ₹{parseInt(net).toLocaleString('en-IN')}
                  </StatNumber>
                  <StatHelpText
                    alignSelf="flex-end"
                    m="0px"
                    color="green.400"
                    fontWeight="bold"
                    ps="6px"
                    fontSize="sm"
                  >
                    +15%
                  </StatHelpText>
                </Flex>
              </Stat>
              <IconBox as="box" h={"40px"} w={"40px"} bg={iconTeal} alignSelf="flex-start">
                <GlobeIcon h={"20px"} w={"20px"} color={iconBoxInside} />
              </IconBox>
            </Flex>
          </CardBody>
        </Card>

        {/* Debt Ratio Card */}
        <Card minH="105px" borderLeft="4px solid #6C63FF" p="16px">
          <CardBody>
            <Flex flexDirection="row" align="center" justify="space-between" w="100%">
              <Stat>
                <StatLabel
                  fontSize="xs"
                  color="gray.400"
                  fontWeight="bold"
                  pb=".2rem"
                  textTransform="uppercase"
                >
                  Debt Ratio
                </StatLabel>
                <Flex align="baseline">
                  <StatNumber fontSize="2xl" color={textColor} fontWeight="bold">
                    {debtRatio.toFixed(2)}
                  </StatNumber>
                  <StatHelpText
                    alignSelf="flex-end"
                    m="0px"
                    color="red.500"
                    fontWeight="bold"
                    ps="6px"
                    fontSize="sm"
                  >
                    -14%
                  </StatHelpText>
                </Flex>
              </Stat>
              <IconBox as="box" h={"40px"} w={"40px"} bg={iconTeal} alignSelf="flex-start">
                <DocumentIcon h={"20px"} w={"20px"} color={iconBoxInside} />
              </IconBox>
            </Flex>
          </CardBody>
        </Card>

        {/* Current Balance Card */}
        <Card minH="105px" borderLeft="4px solid #6C63FF" p="16px">
          <CardBody>
            <Flex flexDirection="row" align="center" justify="space-between" w="100%">
              <Stat>
                <StatLabel
                  fontSize="xs"
                  color="gray.400"
                  fontWeight="bold"
                  pb=".2rem"
                  textTransform="uppercase"
                >
                  Current Balance
                </StatLabel>
                <Flex align="baseline">
                  <StatNumber fontSize="2xl" color={textColor} fontWeight="bold">
                    ₹{parseInt(bal).toLocaleString('en-IN')}
                  </StatNumber>
                  <StatHelpText
                    alignSelf="flex-end"
                    m="0px"
                    color="green.400"
                    fontWeight="bold"
                    ps="6px"
                    fontSize="sm"
                  >
                    +8%
                  </StatHelpText>
                </Flex>
              </Stat>
              <IconBox as="box" h={"40px"} w={"40px"} bg={iconTeal} alignSelf="flex-start">
                <CartIcon h={"20px"} w={"20px"} color={iconBoxInside} />
              </IconBox>
            </Flex>
          </CardBody>
        </Card>
      </SimpleGrid>

      <Grid
        templateColumns={{ md: "1fr", lg: "1.8fr 1.2fr" }}
        templateRows={{ md: "1fr auto", lg: "1fr" }}
        my="26px"
        gap="24px"
      >
        <Card minHeight="290.5px" p="1.2rem">
          <CardBody w="100%">
            <Flex flexDirection={{ sm: "column", lg: "row" }} w="100%">
              <Flex
                flexDirection="column"
                h="100%"
                lineHeight="1.6"
                width={{ lg: "55%" }}
              >
                
                <Text
                  fontSize="lg"
                  color={textColor}
                  fontWeight="bold"
                  pb=".5rem"
                >
                  Welcome {name}
                </Text>
                <Text fontSize="sm" color="gray.400" fontWeight="normal">
                  Find all your financial intelligence here at SHAURYA. Providing credit assessment, net worth tracking, interactive education, and peer-to-peer lending solutions.
                </Text>
                <Spacer />
                <Flex align="center">
                  <Button
                    p="0px"
                    variant="no-hover"
                    bg="transparent"
                    my={{ sm: "1.5rem", lg: "0px" }}
                  >
                    <Text
                      fontSize="sm"
                      color={textColor}
                      fontWeight="bold"
                      cursor="pointer"
                      transition="all .5s ease"
                      my={{ sm: "1.5rem", lg: "0px" }}
                      _hover={{ me: "4px" }}
                    >
                      Read more
                    </Text>
                    <Icon
                      as={BsArrowRight}
                      w="20px"
                      h="20px"
                      fontSize="2xl"
                      transition="all .5s ease"
                      mx=".3rem"
                      cursor="pointer"
                      pt="4px"
                      _hover={{ transform: "translateX(20%)" }}
                    />
                  </Button>
                </Flex>
              </Flex>
              <Spacer />
              <Flex
                bg="teal.300"
                align="center"
                justify="center"
                borderRadius="15px"
                width={{ lg: "40%" }}
                minHeight={{ sm: "250px" }}
              >
                <Image
                  src="https://d1wa5qhtul915h.cloudfront.net/app/uploads/2021/08/Bike-Europe-Stock-Chart.jpg"
                  alt="chakra image"
                  borderRadius="10px"
                  height="250px"
                  objectFit="cover"
                />
              </Flex>
            </Flex>
          </CardBody>
        </Card>
        <Card maxHeight="290.5px" p="1rem">
          <CardBody
            p="0px"
            bgPosition="center"
            bgRepeat="no-repeat"
            w="100%"
            h={{ sm: "200px", lg: "100%" }}
            bgSize="cover"
            position="relative"
            borderRadius="15px"
          >
            <Box
              bg="linear-gradient(360deg, rgba(49, 56, 96, 0.16) 0%, rgba(21, 25, 40, 0.88) 100%)"
              w="100%"
              position="absolute"
              h="inherit"
              borderRadius="inherit"
              ref={overlayRef}
            ></Box>
            <Portal containerRef={overlayRef}>
              <Flex
                flexDirection="column"
                color="white"
                p="1.5rem 1.2rem 0.3rem 1.2rem"
                lineHeight="1.6"
              >
               <BarChart />
                <Spacer />
                <Flex
                  align="center"
                  mt={{ sm: "20px", lg: "40px", xl: "90px" }}
                >
                 
                </Flex>
              </Flex>
            </Portal>
          </CardBody>
        </Card>
      </Grid>
      <Grid
        templateColumns={{ sm: "1fr", lg: "1.3fr 1.7fr" }}
        templateRows={{ sm: "repeat(2, 1fr)", lg: "1fr" }}
        gap="24px"
        mb={{ lg: "26px" }}
      >
        <Card p="16px">
          <CardBody>
            <Flex direction="column" w="100%">
              <Donut />
              <Flex
                direction="column"
                mt="24px"
                mb="36px"
                alignSelf="flex-start"
              >
                <Text
                  fontSize="lg"
                  color={textColor}
                  fontWeight="bold"
                  mb="6px"
                >
                  Expenditure
                </Text>
                <Text fontSize="md" fontWeight="medium" color="gray.400">
                  <Text as="span" color="green.400" fontWeight="bold">
                    (-39%)
                  </Text>{" "}
                  than last month
                </Text>
              </Flex>
              <SimpleGrid gap={{ sm: "12px" }} columns={4}>
                <Flex direction="column">
                  <Flex alignItems="center">
                    <IconBox
                      as="box"
                      h={"30px"}
                      w={"30px"}
                      bg={iconTeal}
                      me="6px"
                    >
                      <RocketIcon h={"15px"} w={"15px"} color={iconBoxInside} />
                    </IconBox>
                    <Text fontSize="sm" color="gray.400" fontWeight="semibold">
                      UPI
                    </Text>
                  </Flex>
                  <Text
                    fontSize="lg"
                    color={textColor}
                    fontWeight="bold"
                    mb="6px"
                    my="6px"
                  >
                    75%
                  </Text>
                  <Progress
                    colorScheme="teal"
                    borderRadius="12px"
                    h="5px"
                    value={75}
                  />
                </Flex>
                <Flex direction="column">
                  <Flex alignItems="center">
                    <IconBox
                      as="box"
                      h={"30px"}
                      w={"30px"}
                      bg={iconTeal}
                      me="6px"
                    >
                      <WalletIcon h={"15px"} w={"15px"} color={iconBoxInside} />
                    </IconBox>
                    <Text fontSize="sm" color="gray.400" fontWeight="semibold">
                      NEFT
                    </Text>
                  </Flex>
                  <Text
                    fontSize="lg"
                    color={textColor}
                    fontWeight="bold"
                    mb="6px"
                    my="6px"
                  >
                    12%
                  </Text>
                  <Progress
                    colorScheme="teal"
                    borderRadius="12px"
                    h="5px"
                    value={12}
                  />
                </Flex>
                <Flex direction="column">
                  <Flex alignItems="center">
                    <IconBox
                      as="box"
                      h={"30px"}
                      w={"30px"}
                      bg={iconTeal}
                      me="6px"
                    >
                      <RocketIcon h={"15px"} w={"15px"} color={iconBoxInside} />
                    </IconBox>
                    <Text fontSize="sm" color="gray.400" fontWeight="semibold">
                      Cheque
                    </Text>
                  </Flex>
                  <Text
                    fontSize="lg"
                    color={textColor}
                    fontWeight="bold"
                    mb="6px"
                    my="6px"
                  >
                    9%
                  </Text>
                  <Progress
                    colorScheme="teal"
                    borderRadius="12px"
                    h="5px"
                    value={9}
                  />
                </Flex>
                <Flex direction="column">
                  <Flex alignItems="center">
                    <IconBox
                      as="box"
                      h={"30px"}
                      w={"30px"}
                      bg={iconTeal}
                      me="6px"
                    >
                      <WalletIcon h={"15px"} w={"15px"} color={iconBoxInside} />
                    </IconBox>
                    <Text fontSize="sm" color="gray.400" fontWeight="semibold">
                      RTGS
                    </Text>
                  </Flex>
                  <Text
                    fontSize="lg"
                    color={textColor}
                    fontWeight="bold"
                    mb="6px"
                    my="6px"
                  >
                    4%
                  </Text>
                  <Progress
                    colorScheme="teal"
                    borderRadius="12px"
                    h="5px"
                    value={4}
                  />
                </Flex>
              </SimpleGrid>
            </Flex>
          </CardBody>
        </Card>
        <Card p="28px 10px 16px 0px" mb={{ sm: "26px", lg: "0px" }}>
          <CardHeader mb="20px" pl="22px">
            <Flex direction="column" alignSelf="flex-start">
              <Text fontSize="lg" color={textColor} fontWeight="bold" mb="6px">
                Monthly Activity Report
              </Text>
              <Text fontSize="md" fontWeight="medium" color="gray.400">
                <Text as="span" color="green.400" fontWeight="bold">
                  (59%) savings
                </Text>{" "}
                last month
              </Text>
            </Flex>
          </CardHeader>
          <Box w="100%" h={{ sm: "300px" }} ps="8px">
            <LineChart />
          </Box>
        </Card>
      </Grid>
      <Grid>
        <Card p="16px" overflowX={{ sm: "scroll", xl: "hidden" }}>
          <CardHeader p="12px 0px 28px 0px">
            <Flex direction="column">
              <Text
                fontSize="lg"
                color={textColor}
                fontWeight="bold"
                pb=".5rem"
              >
                Investments
              </Text>
              <Flex align="center">
                <Icon
                  as={IoCheckmarkDoneCircleSharp}
                  color="teal.300"
                  w={4}
                  h={4}
                  pe="3px"
                />
                <Text fontSize="sm" color="gray.400" fontWeight="normal">
                  <Text fontWeight="bold" as="span">
                    3 Ongoing
                  </Text>{" "}
                  this month.
                </Text>
              </Flex>
            </Flex>
          </CardHeader>
          <Table variant="simple" color={textColor}>
            <Thead>
              <Tr my=".8rem" ps="0px">
                <Th ps="1px" color="gray.400">
                  Investment
                </Th>
                <Th color="gray.400">Investment Value</Th>
                <Th color="gray.400">Current Value</Th>
                <Th color="gray.400">Profit/Loss</Th>
              </Tr>
            </Thead>
            <Tbody>
              <Tr>
                <Td pb=".5rem">Equity</Td>
                <Td pl="8.5rem" pb=".5rem">{dataequity.summary.investmentValue}</Td>
                <Td pl="8.5rem" pb="0.5rem">{dataequity.summary.currentValue}</Td>
                <Td pl="8.5rem" pb="0.5rem">{parseInt(dataequity.summary.currentValue)-parseInt(dataequity.summary.investmentValue)}</Td>
              </Tr>
              <Tr>
                <Td pb=".5rem">ETF</Td>
                <Td pl="8.5rem" pb=".5rem">{dataetf.summary.investmentValue}</Td>
                <Td pl="8.5rem" pb="0.5rem">{dataetf.summary.currentValue}</Td>
                <Td pl="8.5rem" pb="0.5rem">{parseInt(dataetf.summary.currentValue)-parseInt(dataetf.summary.investmentValue)}</Td>
              </Tr>
              <Tr>
                <Td pb=".5rem">Mutual Funds</Td>
                <Td pl="8.5rem" pb=".5rem">{datamutualfund.summary.investmentValue}</Td>
                <Td pl="8.5rem" pb="0.5rem">{datamutualfund.summary.currentValue}</Td>
                <Td pl="8.5rem" pb="0.5rem">{parseInt(datamutualfund.summary.currentValue)-parseInt(datamutualfund.summary.investmentValue)}</Td>
              </Tr>
            </Tbody>
          </Table>
        </Card>
      </Grid>
    </Flex>
  );
}